apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: python-tuyndndu
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/chetna14manku_org/python-tuyndndu:790937df8714a5f6ba2a102057025482e9e2a579@sha256:b66aae495663f3687928707330460a92ef56be5e37cc033e78499c10f267b66b
          name: container-image
